[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_type = "semver"
version = "0.0.3"
update_changelog_on_bump = true
major_version_zero = true
version_files = ["README.md"]
